before:
  hooks:
    - go mod tidy
    - yarn --cwd ui install
    - yarn --cwd ui build
    - cp -r ui/dist/app/* server/static

builds:
  - id: kubectl-argo-rollouts
    main: ./cmd/kubectl-argo-rollouts
    binary: kubectl-argo-rollouts
    ldflags:
      - -s -w
      - -X 'github.com/argoproj/argo-rollouts/utils/version.version={{.Version}}'
      - -X 'github.com/argoproj/argo-rollouts/utils/version.buildDate={{.Date}}'
      - -X 'github.com/argoproj/argo-rollouts/utils/version.gitCommit={{.Commit}}'
      - -X 'github.com/argoproj/argo-rollouts/utils/version.gitTreeState=clean'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: kubectl-argo-rollouts
    format: binary
    builds:
      - kubectl-argo-rollouts
    name_template: "kubectl-argo-rollouts-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'argo-rollouts-checksums.txt'

snapshot:
  name_template: "{{ .Version }}-SNAPSHOT-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  prerelease: auto
  draft: false